### ISSUE TITLE
Polygon breaks in polar (laea) projection

### ISSUE THREAD

**Issue by Maschette** [AustralianAntarcticDivision/measoshapes#1]
Hi, 
Looking at the polygons, in lonlat there is a split in 3 of the assessment units at 180. These splits are also in the polar projection. So what is 3 management units looks like it is 6.

Is it possible to get the polar projection with the polygons joined? 

``` r
library(measoshapes)
#> Loading required package: sf
#> Linking to GEOS 3.6.1, GDAL 2.2.3, PROJ 4.9.3
plot(measo_regions05_coastline)
```

![](https://i.imgur.com/UPajFtK.png)

<sup>Created on 2019-09-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mdsumner** [comment]
Can do this: 

```R
library(dplyr)
x <- measo_regions05_coastline %>% 
  group_by(name) %>% 
  summarize()
```

I think I intended to make the polar versions integrated like that as in aceecostats, but the fact is I got used to working with it this way ...

**Comment by mdsumner** [comment]
btw fwiw, that's equivalent to 

```R
library(dplyr)
x <- measo_regions05_coastline %>% 
  group_by(name) %>% 
  summarize(geometry = st_union(geometry))

```

sf provides the summarize() union by default because it means you don't need to name the geometry column
